### PR TITLE
[WIP] Fix build

### PR DESCRIPTION
**Pull request by jopasserat**
- [x] add missing boost libraries in docker build
- [x] bash utility script to regenerate boost cmake when new libraries come in
- [x] builds fine
- [x] C++ unit tests
- [ ] Python tests

### CODE REVIEW

**Comment by jopasserat** [comment]
python error: 
```
(venv-tf-py3) root@77e71fdc9e56:/home/he-transformer/examples# NGRAPH_TF_BACKEND=HE_SEAL_CKKS python axpy.py
2019-06-06 11:19:06.978497: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2904000000 Hz
2019-06-06 11:19:06.979087: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x3179c30 executing computations on platform Host. Devices:
2019-06-06 11:19:06.979143: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "/home/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: NGRAPH_TF_BACKEND: HE_SEAL_CKKS is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "axpy.py", line 27, in <module>
    f_val = sess.run(f, feed_dict={b: np.ones((2, 2)), c: np.array(5, )})
  File "/home/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: NGRAPH_TF_BACKEND: HE_SEAL_CKKS is not supported
```

**Comment by fboemer** [comment]
Try `HE_SEAL` rather than `HE_SEAL_CKKS`. (See https://github.com/NervanaSystems/he-transformer/pull/196)

**Comment by jopasserat** [comment]
works! what scheme does that default to? still CKKS?

**Comment by fboemer** [comment]
> works! what scheme does that default to? still CKKS?

Yep. This is the only scheme we currently support

**Comment by fboemer** [comment]
@jopasserat, see if this works for you https://github.com/NervanaSystems/he-transformer/pull/201

**Comment by jopasserat** [comment]
all good for me! I guess we can close this PR now that it's been superseded by #201

**Pull request closed without merging**
